SELECT * FROM sales_orders;

-- WHERE (Filtering)

-- Q1. Retrieve all orders where the payment method is 'UPI' and the order was delivered.
SELECT * FROM sales_orders
WHERE payment_method = 'UPI'
  AND status = 'Delivered';

-- Q2. List all orders placed between Jan 1, 2024 and Mar 31, 2024 from Maharashtra (MH) with total_amount > 5000.

SELECT * FROM sales_orders
WHERE state = 'MH'
  AND order_date BETWEEN '2024-01-01' AND '2024-03-31'
  AND total_amount > 5000;


-- Q3. Find all orders where the product belongs to the 'Electronics' category but is NOT a Mobile or Laptop (exclude sub_category = 'Mobiles' and 'Laptops').
SELECT * FROM sales_orders
WHERE category = 'Electronics'
  AND NOT (sub_category = 'Mobiles' OR sub_category = 'Laptops');


SELECT * FROM sales_orders
WHERE category = 'Electronics'
  AND sub_category NOT IN ('Mobiles', 'Laptops');

-- Q4. Get all orders where customer name starts with 'P', total_amount is between ₹1000 and ₹50000, and the order is either Delivered or Returned.

SELECT * FROM sales_orders
WHERE customer_name LIKE 'P%'
  AND total_amount BETWEEN 1000 AND 5000
  AND status IN ('Delivered', 'Returned');

-- Q5. Find all orders placed in the second half of 2024 (July–December) where unit_price differs from total_amount (i.e. quantity > 1) and the order was NOT cancelled.

SELECT * FROM sales_orders
WHERE order_date >= '2024-07-01'
  AND unit_price <> total_amount
  AND status <> 'Cancelled';


-- GROUP BY
-- Q6. Find the total revenue generated by each category.
SELECT category, SUM(total_amount) AS total_revenue
FROM sales_orders
GROUP BY category
ORDER BY total_revenue DESC;

-- Q7. Count the number of orders placed by each sales_rep, grouped by order status.
SELECT sales_rep, status, COUNT(*) as number_of_orders
FROM sales_orders
GROUP BY sales_rep, status
ORDER BY sales_rep, status;

-- Q8. For each state, find the most expensive order (max total_amount) and the total number of orders.
SELECT state, 
	   MAX(total_amount) AS maximum,
	   COUNT(*) AS no_of_orders
FROM sales_orders
GROUP BY state
ORDER BY maximum DESC;

-- Q9.Group orders by month (extracted from order_date) and category, and find total quantity sold and total revenue for each combination.

SELECT MONTH(order_date) AS order_month, 
	   category, 
	   SUM(quantity) AS total_quantity, 
	   SUM(total_amount) AS total_revenue
FROM sales_orders
GROUP BY MONTH(order_date), category
ORDER BY order_month, category;

-- Q10. Find each city's contribution to total revenue as a percentage of overall revenue, grouped by city. (IMP)

SELECT city,
       SUM(total_amount) AS city_revenue,
       ROUND(SUM(total_amount) * 100.0 /
         (SELECT SUM(total_amount) FROM sales_orders), 2) AS pct_of_total
FROM sales_orders
GROUP BY city
ORDER BY pct_of_total DESC;


-- HAVING
-- Q11. Show categories where the total number of orders is greater than 5.

SELECT category, COUNT(*) AS total_orders
FROM sales_orders
GROUP BY category
HAVING COUNT(*) > 5;

-- Q12. List sales reps whose total sales revenue exceeds ₹1,00,000.

SELECT sales_rep, SUM(total_amount) AS sale_revenue
FROM sales_orders
GROUP BY sales_rep
HAVING SUM(total_amount) > 100000;

-- (Q13). Find states that have at least 1 cancelled order AND whose total revenue from delivered orders is more than ₹50,000. (IMP)
SELECT state,
	SUM(CASE WHEN status = 'Delievered' THEN total_amount ELSE 0 END) AS delivered_revenue,
	SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS cancels
FROM sales_orders
GROUP BY state
HAVING SUM(CASE WHEN status = 'Delievered' THEN total_amount ELSE 0 END) >=1 AND SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) > 50000;


-- Q14. Find sub-categories where the average unit price is above the overall average unit price across all orders.

SELECT sub_category, AVG(unit_price) as avg_subcat_unit, (SELECT AVG(unit_price) FROM sales_orders) as avg_orders_price
FROM sales_orders
GROUP BY sub_category
HAVING AVG(unit_price) > (SELECT AVG(unit_price) FROM sales_orders)
ORDER BY avg_subcat_unit DESC;

-- Q15. List customers who have placed more than 1 order AND whose average order value is less than ₹10,000, but have at least one order worth more than ₹5,000. (IMP)
SELECT customer_name, count(*) as cnt_orders,
AVG(total_amount) as avg_total_amount,
SUM(CASE WHEN total_amount > 5000 THEN total_amount ELSE 0 END) AS cnt
FROM sales_orders
GROUP BY customer_name
HAVING COUNT(*) > 1 
  AND AVG(total_amount) < 10000
  AND SUM(CASE WHEN total_amount > 5000 THEN total_amount ELSE 0 END) > 5000;


SELECT customer_name,
       COUNT(*) AS total_orders,
       ROUND(AVG(total_amount), 2) AS avg_order_val,
       MAX(total_amount) AS max_order
FROM sales_orders
GROUP BY customer_name
HAVING COUNT(*) > 1
   AND AVG(total_amount) < 10000
   AND MAX(total_amount) > 5000;


 -- AGGREGATE FUNCTIONS
 -- Q16. Find the total revenue, total number of orders, and average order value across all orders.

SELECT SUM(total_amount) AS total_revenue,
	   COUNT(*) AS no_of_orders,
	   ROUND(AVG(total_amount),2) AS avg_order_value
FROM sales_orders;

-- Q17. For each payment method, find the total revenue, number of orders, and the highest single-order value.
SELECT payment_method,
	   SUM(total_amount) AS total_revenue,
	   COUNT(*) AS no_of_orders,
	   MAX(total_amount) as highest_order
FROM sales_orders
GROUP BY payment_method;

-- Q18. Calculate the total quantity sold per category and the percentage share of each category's quantity out of the total.

SELECT category, 
	   SUM(quantity) AS quantity_sold, 
	   ROUND(SUM(quantity)*100.0/(SELECT SUM(quantity) FROM sales_orders),2) AS prct_share_qty
FROM sales_orders
GROUP BY category;

-- Q19. Find the sales rep with the highest average order value among those who have handled at least 5 orders.
SELECT sales_rep, 
       COUNT(*) AS total_orders, 
	   AVG(total_amount) AS avg_order_amount
FROM sales_orders
GROUP BY sales_rep
HAVING COUNT(*) >= 5
ORDER BY avg_order_amount DESC
LIMIT 1;

-- (Q20. For each month, find the category that generated the highest revenue. Show month, category, and revenue.
SELECT month, category, revenue
FROM (
  SELECT MONTH(order_date) AS month,
         category,
         SUM(total_amount) AS revenue,
         RANK() OVER (PARTITION BY MONTH(order_date)
                      ORDER BY SUM(total_amount) DESC) AS rnk
  FROM sales_orders
  GROUP BY MONTH(order_date), category
) ranked
WHERE rnk = 1
ORDER BY month;

-- Q21. Retrieve the top 5 orders by total_amount in descending order.

SELECT * 
FROM sales_orders
ORDER BY total_amount DESC
LIMIT 5;

-- Q22. Implement pagination: show the 3rd page of orders (page size = 10), ordered by order_date ascending.

SELECT * 
FROM sales_orders
ORDER BY order_date
LIMIT 10
OFFSET 20;


select * from sales_orders

-- Q23. Get the 2nd and 3rd most expensive products (by unit_price) in the Electronics category.
SELECT DISTINCT product_name, unit_price
FROM sales_orders
WHERE category = 'Electronics'
ORDER BY unit price DESC
LIMIT 2
OFFSET 1;


-- (Q24). For each sales rep, show only their single highest-value order. Use a correlated subquery with LIMIT (without window functions).

SELECT s1.*
FROM sales_orders s1
WHERE order_id = (
  SELECT order_id FROM sales_orders s2
  WHERE s2.sales_rep = s1.sales_rep
  ORDER BY total_amount DESC
  LIMIT 1
)
ORDER BY s1.sales_rep;

-- Q25. Find the bottom 5 cities by total revenue, but only considering cities that have placed at least 2 orders. Show city, order count, and total revenu

SELECT city,
       COUNT(*) AS order_count,
       SUM(total_amount) AS total_revenue
FROM sales_orders
GROUP BY city
HAVING COUNT(*) >= 2
ORDER BY total_revenue ASC
LIMIT 5;